# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: salassam <salassam@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/11/02 20:33:20 by salassam          #+#    #+#              #
#    Updated: 2015/11/02 20:33:24 by salassam         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	=	do-op

SRC		=	ft_atoi.c ft_putchar.c ft_putnbr.c operation.c main.c

all		:	$(NAME)

$(NAME)	:
	gcc -o $(NAME) $(SRC) $(FLG)

clean	:
	/bin/rm -f $(NAME)
