# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: salassam <salassam@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/11/02 20:36:00 by salassam          #+#    #+#              #
#    Updated: 2015/11/02 20:36:01 by salassam         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	=	ft_advanced_do-op

SRC		=	main.c operation.c ft_atoi.c ft_putchar.c ft_putnbr.c

FLG		=	-Wall -Wextra -Werror

all: $(NAME)

$(NAME):
	gcc -o $(NAME) $(SRC) $(FLG)

clean:
	/bin/rm -f $(NAME)
